name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🚀 Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            export PATH=$PATH:/usr/local/bin:/usr/bin:/bin:/home/ubuntu/.nvm/versions/node/v22.17.0/bin/
            cd /home/ubuntu/Turk-tili-api
            git pull origin main
            yarn install
            npx prisma generate
            npx prisma migrate deploy
            yarn build
            pm2 restart backend || pm2 start dist/main.js --name backend
