name: Deploy Backend

on:
  push:
    branches:
      - main # agar branch boshqa bo‘lsa, o‘zgartir

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🚀 Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            export PATH=$PATH:/usr/local/bin:/usr/bin:/bin:/home/ubuntu/.nvm/versions/node/v22.17.0/bin/
            cd /home/ubuntu/Turk-tili-api
            git pull origin main
            /home/ubuntu/.nvm/versions/node/v22.17.0/bin/yarn install
            /home/ubuntu/.nvm/versions/node/v22.17.0/bin/yarn build
            /home/ubuntu/.nvm/versions/node/v22.17.0/bin/pm2 restart backend || /home/ubuntu/.nvm/versions/node/v22.17.0/bin/pm2 start dist/main.js --name backend
