name: Deploy Backend

on:
  push:
    branches:
      - main  # agar branch boshqa bo‘lsa, o‘zgartir

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v3

    - name: 🚀 Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/ubuntu/Turk-tili-api
          git pull origin main
          yarn install
          yarn build
          pm2 restart backend || pm2 start dist/main.js --name backend
